/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.furb.interfaces;

import br.furb.nucleo.MVM;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.IOException;
import javax.swing.JScrollBar;

/**
 *
 * @author Gabriel Bernardi
 */
public class TesteDepuracao extends javax.swing.JFrame {

    /**
     * Creates new form TesteDepuracao
     */
    public TesteDepuracao() {
        initComponents();
        this.inicializarFrame();
    }
    
    private void inicializarFrame(){
        this.jtaCod.setBorder(new NumberedBorder());
        this.jtaPos.setEditable(false);
        this.setBreakpoint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbDepurar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCod = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaPos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbDepurar.setText("Depurar");
        jbDepurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDepurarActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBar(jScrollPane2.getVerticalScrollBar());

        jtaCod.setColumns(20);
        jtaCod.setRows(5);
        jScrollPane1.setViewportView(jtaCod);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jtaPos.setColumns(20);
        jtaPos.setRows(5);
        jScrollPane2.setViewportView(jtaPos);
        jtaPos.getAccessibleContext().setAccessibleParent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbDepurar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbDepurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbDepurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDepurarActionPerformed
        this.jtaPos.append("\n");
        this.setBreakpoint();
        this.depurarExecucaoBreakPoint();
    }//GEN-LAST:event_jbDepurarActionPerformed

    private void setBreakpoint(){
        int qtdLinhasDepuradas = this.jtaPos.getLineCount();
        this.jtaPos.setText("");
        for (int i = 1; i < qtdLinhasDepuradas; i++) {
            this.jtaPos.append("\n");
        }
        this.jtaPos.append("✓");
        this.moverScroll();
    }
    
    private void moverScroll(){
//        this.jScrollPane1.getVerticalScrollBar().setValue(this.jtaPos.getHeight());
//        if (jtaPos.getLineCount() > 15){
//            this.jtaCod.setRows(jtaPos.getLineCount());
//            this.jtaCod.setCaretPosition(jtaPos.getLineCount());
            
//        }
    }
    
    private void depurarExecucaoBreakPoint(){
//        String linhas[] = this.jtaCod.getText().split("\n");
//        String instrucao = linhas[this.jtaPos.getLineCount()-2];
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesteDepuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesteDepuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesteDepuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesteDepuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteDepuracao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbDepurar;
    private javax.swing.JTextArea jtaCod;
    private javax.swing.JTextArea jtaPos;
    // End of variables declaration//GEN-END:variables
}
