/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.furb.view;

import br.furb.nucleo.MVM;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Bernardi
 */
public class CodeCompiler extends javax.swing.JFrame {
    
    private String code;
    
    /**
     * Creates new form CodeCompiler
     */
    public CodeCompiler() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void init(String code){
        this.code = code;
        this.codigoFonteJTA.setText(code);
        this.codigoFonteJTA.enable(false);
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fundoJP = new javax.swing.JPanel();
        ferramentaJTB = new javax.swing.JToolBar();
        stepJB = new javax.swing.JButton();
        runJB = new javax.swing.JButton();
        stopJB = new javax.swing.JButton();
        codigoFonteJSP = new javax.swing.JScrollPane();
        codigoFonteJTA = new javax.swing.JTextArea();
        linhaJTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fundoJP.setPreferredSize(new java.awt.Dimension(800, 600));
        fundoJP.setLayout(new java.awt.GridBagLayout());

        ferramentaJTB.setFloatable(false);
        ferramentaJTB.setRollover(true);
        ferramentaJTB.setPreferredSize(new java.awt.Dimension(100, 10));

        stepJB.setText("Step");
        stepJB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepJB.setPreferredSize(new java.awt.Dimension(70, 35));
        stepJB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stepJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepJBActionPerformed(evt);
            }
        });
        ferramentaJTB.add(stepJB);

        runJB.setText("Run");
        runJB.setFocusable(false);
        runJB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        runJB.setPreferredSize(new java.awt.Dimension(70, 35));
        runJB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        runJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runJBActionPerformed(evt);
            }
        });
        ferramentaJTB.add(runJB);

        stopJB.setText("Stop");
        stopJB.setFocusable(false);
        stopJB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stopJB.setPreferredSize(new java.awt.Dimension(70, 35));
        stopJB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stopJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopJBActionPerformed(evt);
            }
        });
        ferramentaJTB.add(stopJB);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        fundoJP.add(ferramentaJTB, gridBagConstraints);

        codigoFonteJTA.setColumns(20);
        codigoFonteJTA.setRows(5);
        codigoFonteJSP.setViewportView(codigoFonteJTA);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.9;
        fundoJP.add(codigoFonteJSP, gridBagConstraints);

        linhaJTF.setEditable(false);
        linhaJTF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 1.0;
        fundoJP.add(linhaJTF, gridBagConstraints);

        getContentPane().add(fundoJP, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stepJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepJBActionPerformed
        
    }//GEN-LAST:event_stepJBActionPerformed

    private void runJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runJBActionPerformed
        try {
            MVM.traduzirCodigoFonte(this.code, 0, true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Falha na execução do programa.\nErro: " + e.getMessage());
        }
    }//GEN-LAST:event_runJBActionPerformed

    private void stopJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopJBActionPerformed

    }//GEN-LAST:event_stopJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CodeCompiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CodeCompiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CodeCompiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CodeCompiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodeCompiler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane codigoFonteJSP;
    private javax.swing.JTextArea codigoFonteJTA;
    private javax.swing.JToolBar ferramentaJTB;
    private javax.swing.JPanel fundoJP;
    private javax.swing.JTextField linhaJTF;
    private javax.swing.JButton runJB;
    private javax.swing.JButton stepJB;
    private javax.swing.JButton stopJB;
    // End of variables declaration//GEN-END:variables
}
